apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-aws-credentials
  namespace: jenkins
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 128Mi
  storageClassName: aws-efs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-aws-kubeconfig
  namespace: jenkins
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 128Mi
  storageClassName: aws-efs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-slave-pvc-maven
  namespace: jenkins
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: aws-efs
